// flow-typed signature: 44d9350d6109cf82d9bc2b13f87fd547
// flow-typed version: <<STUB>>/hex-rgb_v^1.0.0/flow_v0.166.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hex-rgb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hex-rgb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hex-rgb/index' {
  declare module.exports: $Exports<'hex-rgb'>;
}
declare module 'hex-rgb/index.js' {
  declare module.exports: $Exports<'hex-rgb'>;
}
