name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: CultureHQ/actions-yarn@v1.0.1

    - name: Tests
      run: |
        yarn install
        yarn eslint .
        yarn flow
        yarn test
        yarn build
    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./dist http://www.brianzchen.com/ --token ${{secrets.SURGE}}
